# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: #demo-user
  CLOUD_SQL_PASSWORD: #welcome123
  CLOUD_SQL_DATABASE_NAME: #test_db
  CLOUD_SQL_CONNECTION_NAME: #test-project-315203:us-central1:demo-db
# [END gae_python37_cloudsql_config]